"""
Base Strategy Module.

Defines the abstract base class and common components for all trading strategies.
All strategies inherit from BaseStrategy and implement specific trading logic.
"""

import pandas as pd
import numpy as np
from abc import ABC, abstractmethod
from dataclasses import dataclass, field, asdict
from typing import Dict, List, Optional, Tuple, Any, Union
from enum import Enum
from datetime import datetime
import logging
import json

logger = logging.getLogger(__name__)


class SignalType(Enum):
    """Types of trading signals."""
    LONG = "long"       # Buy/enter long position
    SHORT = "short"     # Sell/enter short position
    EXIT = "exit"       # Exit current position
    HOLD = "hold"       # No action


class PositionType(Enum):
    """Types of positions."""
    FLAT = "flat"       # No position
    LONG = "long"       # Long position
    SHORT = "short"     # Short position


@dataclass
class StrategySignal:
    """
    Represents a trading signal generated by a strategy.
    """
    timestamp: datetime
    signal_type: SignalType
    price: float
    confidence: float = 1.0  # Confidence level (0-1)
    reason: str = ""         # Human-readable reason
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict:
        return {
            'timestamp': self.timestamp.isoformat() if isinstance(self.timestamp, datetime) else str(self.timestamp),
            'signal_type': self.signal_type.value,
            'price': self.price,
            'confidence': self.confidence,
            'reason': self.reason,
            'metadata': self.metadata
        }


@dataclass
class Position:
    """
    Represents a trading position.
    """
    entry_timestamp: datetime
    entry_price: float
    position_type: PositionType
    size: float = 1.0
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    trailing_stop: Optional[float] = None
    trailing_stop_price: Optional[float] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def update_trailing_stop(self, current_price: float, trailing_pct: float) -> None:
        """Update trailing stop based on current price."""
        if self.position_type == PositionType.LONG:
            new_stop = current_price * (1 - trailing_pct / 100)
            if self.trailing_stop_price is None or new_stop > self.trailing_stop_price:
                self.trailing_stop_price = new_stop
        elif self.position_type == PositionType.SHORT:
            new_stop = current_price * (1 + trailing_pct / 100)
            if self.trailing_stop_price is None or new_stop < self.trailing_stop_price:
                self.trailing_stop_price = new_stop
    
    def check_exit_conditions(self, current_price: float) -> Tuple[bool, str]:
        """Check if any exit condition is triggered."""
        if self.position_type == PositionType.LONG:
            # Stop loss
            if self.stop_loss and current_price <= self.stop_loss:
                return True, "stop_loss"
            # Take profit
            if self.take_profit and current_price >= self.take_profit:
                return True, "take_profit"
            # Trailing stop
            if self.trailing_stop_price and current_price <= self.trailing_stop_price:
                return True, "trailing_stop"
        
        elif self.position_type == PositionType.SHORT:
            # Stop loss
            if self.stop_loss and current_price >= self.stop_loss:
                return True, "stop_loss"
            # Take profit
            if self.take_profit and current_price <= self.take_profit:
                return True, "take_profit"
            # Trailing stop
            if self.trailing_stop_price and current_price >= self.trailing_stop_price:
                return True, "trailing_stop"
        
        return False, ""
    
    def calculate_pnl(self, exit_price: float) -> float:
        """Calculate profit/loss for the position."""
        if self.position_type == PositionType.LONG:
            return (exit_price - self.entry_price) / self.entry_price * self.size
        elif self.position_type == PositionType.SHORT:
            return (self.entry_price - exit_price) / self.entry_price * self.size
        return 0.0


@dataclass
class TradeResult:
    """
    Represents the result of a completed trade.
    """
    entry_timestamp: datetime
    exit_timestamp: datetime
    entry_price: float
    exit_price: float
    position_type: PositionType
    size: float
    pnl_pct: float
    pnl_absolute: float
    exit_reason: str
    holding_period: int  # In candles/periods
    fees: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict:
        return {
            'entry_timestamp': str(self.entry_timestamp),
            'exit_timestamp': str(self.exit_timestamp),
            'entry_price': self.entry_price,
            'exit_price': self.exit_price,
            'position_type': self.position_type.value,
            'size': self.size,
            'pnl_pct': self.pnl_pct,
            'pnl_absolute': self.pnl_absolute,
            'exit_reason': self.exit_reason,
            'holding_period': self.holding_period,
            'fees': self.fees,
            'metadata': self.metadata
        }


@dataclass
class StrategyParameters:
    """
    Base class for strategy parameters.
    
    All strategy-specific parameters should inherit from this.
    Contains common parameters used across all strategies.
    """
    # Execution parameters
    entry_confirmation: int = 1      # Candles to confirm entry
    exit_confirmation: int = 1       # Candles to confirm exit
    cooldown_period: int = 5         # Candles between trades
    
    # Risk management parameters
    stop_loss_pct: float = 2.0       # Stop loss percentage
    take_profit_pct: float = 4.0     # Take profit percentage
    trailing_stop_pct: float = 1.5   # Trailing stop percentage
    use_trailing_stop: bool = True   # Whether to use trailing stop
    
    max_loss_per_trade_pct: float = 2.0   # Max loss per trade
    max_trades_per_day: int = 10          # Max trades per day
    position_size_pct: float = 10.0       # Position size as % of capital
    risk_per_trade_pct: float = 2.0       # Risk per trade as % of capital
    
    # Time-based parameters
    trading_start_hour: int = 0      # Trading session start (0-23)
    trading_end_hour: int = 24       # Trading session end (0-24)
    max_holding_time: int = 240      # Max holding time in candles
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert parameters to dictionary."""
        return asdict(self)
    
    @classmethod
    def from_dict(cls, params: Dict[str, Any]) -> 'StrategyParameters':
        """Create parameters from dictionary."""
        return cls(**{k: v for k, v in params.items() if k in cls.__dataclass_fields__})
    
    def get_bounds(self) -> Dict[str, Tuple[float, float]]:
        """Get parameter bounds for optimization."""
        return {
            'entry_confirmation': (1, 5),
            'exit_confirmation': (1, 5),
            'cooldown_period': (1, 30),
            'stop_loss_pct': (0.5, 5.0),
            'take_profit_pct': (1.0, 10.0),
            'trailing_stop_pct': (0.5, 3.0),
            'max_loss_per_trade_pct': (0.5, 3.0),
            'max_trades_per_day': (1, 20),
            'position_size_pct': (1.0, 20.0),
            'risk_per_trade_pct': (0.5, 5.0),
            'max_holding_time': (5, 1440)
        }


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    
    Strategies implement the generate_signal method to produce
    trading signals based on OHLCV data and features.
    
    Key design principles:
    - Strategy logic is FIXED (human-defined rules)
    - Only PARAMETERS can be adjusted by ML
    - Clear separation between strategy logic and parameters
    """
    
    def __init__(
        self,
        name: str,
        parameters: Optional[StrategyParameters] = None,
        initial_capital: float = 100000.0,
        trading_fee_pct: float = 0.001
    ):
        """
        Initialize the strategy.
        
        Args:
            name: Strategy identifier
            parameters: Strategy parameters
            initial_capital: Starting capital
            trading_fee_pct: Trading fee as percentage
        """
        self.name = name
        self.parameters = parameters or StrategyParameters()
        self.initial_capital = initial_capital
        self.trading_fee_pct = trading_fee_pct
        
        # State tracking
        self.current_position: Optional[Position] = None
        self.trades: List[TradeResult] = []
        self.signals: List[StrategySignal] = []
        self.daily_trade_count: Dict[str, int] = {}
        self.last_trade_index: int = -100  # For cooldown tracking
        
        # Capital tracking
        self.current_capital = initial_capital
        self.peak_capital = initial_capital
    
    def update_parameters(self, params: Dict[str, Any]) -> None:
        """
        Update strategy parameters.
        
        Args:
            params: Dictionary of parameter names and values to update
        """
        for key, value in params.items():
            if hasattr(self.parameters, key):
                setattr(self.parameters, key, value)
    
    @abstractmethod
    def generate_signal(
        self,
        df: pd.DataFrame,
        current_idx: int
    ) -> StrategySignal:
        """
        Generate trading signal based on current market state.
        
        THIS METHOD DEFINES THE STRATEGY LOGIC.
        It should NOT be modified by ML - only parameters should change.
        
        Args:
            df: DataFrame with OHLCV and features
            current_idx: Current index in the DataFrame
            
        Returns:
            StrategySignal indicating the trading action
        """
        pass
    
    @abstractmethod
    def get_strategy_specific_params(self) -> Dict[str, Any]:
        """Get strategy-specific parameters."""
        pass
    
    @abstractmethod
    def set_strategy_specific_params(self, params: Dict[str, Any]) -> None:
        """Set strategy-specific parameters."""
        pass
    
    def process_candle(
        self,
        df: pd.DataFrame,
        current_idx: int
    ) -> Tuple[Optional[StrategySignal], Optional[TradeResult]]:
        """
        Process a single candle and manage positions.
        
        Args:
            df: DataFrame with OHLCV and features
            current_idx: Current index
            
        Returns:
            Tuple of (signal if generated, trade result if closed)
        """
        current_row = df.iloc[current_idx]
        current_price = current_row['close']
        current_time = df.index[current_idx]
        
        trade_result = None
        signal = None
        
        # Check if in trading hours
        if hasattr(current_time, 'hour'):
            if not self._is_trading_hours(current_time.hour):
                return None, None
        
        # Update trailing stop if in position
        if self.current_position and self.parameters.use_trailing_stop:
            self.current_position.update_trailing_stop(
                current_price,
                self.parameters.trailing_stop_pct
            )
        
        # Check exit conditions for existing position
        if self.current_position:
            should_exit, exit_reason = self.current_position.check_exit_conditions(
                current_price
            )
            
            # Check max holding time
            holding_time = current_idx - self.current_position.metadata.get('entry_idx', 0)
            if holding_time >= self.parameters.max_holding_time:
                should_exit = True
                exit_reason = "max_holding_time"
            
            if should_exit:
                trade_result = self._close_position(
                    current_time,
                    current_price,
                    exit_reason,
                    holding_time
                )
        
        # Generate signal if not in position
        if not self.current_position:
            # Check cooldown
            if current_idx - self.last_trade_index < self.parameters.cooldown_period:
                return None, trade_result
            
            # Check daily trade limit
            date_key = str(current_time.date()) if hasattr(current_time, 'date') else str(current_time)[:10]
            if self.daily_trade_count.get(date_key, 0) >= self.parameters.max_trades_per_day:
                return None, trade_result
            
            # Generate signal
            signal = self.generate_signal(df, current_idx)
            
            if signal.signal_type in [SignalType.LONG, SignalType.SHORT]:
                self._open_position(signal, current_idx, current_time, current_price)
                self.daily_trade_count[date_key] = self.daily_trade_count.get(date_key, 0) + 1
                self.signals.append(signal)
        
        return signal, trade_result
    
    def _open_position(
        self,
        signal: StrategySignal,
        idx: int,
        timestamp: datetime,
        price: float
    ) -> None:
        """Open a new position."""
        position_type = (
            PositionType.LONG if signal.signal_type == SignalType.LONG 
            else PositionType.SHORT
        )
        
        # Calculate position size based on risk
        position_size = self._calculate_position_size(price)
        
        # Calculate stop loss and take profit
        if position_type == PositionType.LONG:
            stop_loss = price * (1 - self.parameters.stop_loss_pct / 100)
            take_profit = price * (1 + self.parameters.take_profit_pct / 100)
        else:
            stop_loss = price * (1 + self.parameters.stop_loss_pct / 100)
            take_profit = price * (1 - self.parameters.take_profit_pct / 100)
        
        self.current_position = Position(
            entry_timestamp=timestamp,
            entry_price=price,
            position_type=position_type,
            size=position_size,
            stop_loss=stop_loss,
            take_profit=take_profit,
            trailing_stop=self.parameters.trailing_stop_pct,
            metadata={
                'entry_idx': idx,
                'signal_confidence': signal.confidence,
                'signal_reason': signal.reason
            }
        )
        
        self.last_trade_index = idx
        logger.debug(f"Opened {position_type.value} position at {price}")
    
    def _close_position(
        self,
        timestamp: datetime,
        price: float,
        reason: str,
        holding_period: int
    ) -> TradeResult:
        """Close current position and record the trade."""
        if not self.current_position:
            raise ValueError("No position to close")
        
        # Calculate PnL
        pnl_pct = self.current_position.calculate_pnl(price)
        
        # Calculate fees
        entry_fee = self.current_position.entry_price * self.trading_fee_pct
        exit_fee = price * self.trading_fee_pct
        total_fees = (entry_fee + exit_fee) * self.current_position.size
        
        # Net PnL after fees
        pnl_absolute = (pnl_pct * self.current_capital) - total_fees
        net_pnl_pct = pnl_pct - (total_fees / self.current_capital)
        
        # Update capital
        self.current_capital += pnl_absolute
        self.peak_capital = max(self.peak_capital, self.current_capital)
        
        # Create trade result
        trade_result = TradeResult(
            entry_timestamp=self.current_position.entry_timestamp,
            exit_timestamp=timestamp,
            entry_price=self.current_position.entry_price,
            exit_price=price,
            position_type=self.current_position.position_type,
            size=self.current_position.size,
            pnl_pct=net_pnl_pct * 100,  # Convert to percentage
            pnl_absolute=pnl_absolute,
            exit_reason=reason,
            holding_period=holding_period,
            fees=total_fees,
            metadata=self.current_position.metadata
        )
        
        self.trades.append(trade_result)
        self.current_position = None
        
        logger.debug(f"Closed position at {price}, PnL: {net_pnl_pct:.2%}, Reason: {reason}")
        
        return trade_result
    
    def _calculate_position_size(self, price: float) -> float:
        """Calculate position size based on risk parameters."""
        # Position sizing based on fixed percentage of capital
        position_value = self.current_capital * (self.parameters.position_size_pct / 100)
        return position_value / price
    
    def _is_trading_hours(self, hour: int) -> bool:
        """Check if current hour is within trading hours."""
        if self.parameters.trading_start_hour <= self.parameters.trading_end_hour:
            return self.parameters.trading_start_hour <= hour < self.parameters.trading_end_hour
        else:
            # Wraps around midnight
            return hour >= self.parameters.trading_start_hour or hour < self.parameters.trading_end_hour
    
    def reset(self) -> None:
        """Reset strategy state."""
        self.current_position = None
        self.trades = []
        self.signals = []
        self.daily_trade_count = {}
        self.last_trade_index = -100
        self.current_capital = self.initial_capital
        self.peak_capital = self.initial_capital
    
    def get_all_parameters(self) -> Dict[str, Any]:
        """Get all parameters (base + strategy-specific)."""
        params = self.parameters.to_dict()
        params.update(self.get_strategy_specific_params())
        return params
    
    def set_all_parameters(self, params: Dict[str, Any]) -> None:
        """Set all parameters from dictionary."""
        # Preserve the concrete parameters class (many strategies use a
        # StrategyParameters subclass with extra fields).
        param_cls = type(self.parameters)

        # Update parameters (base + strategy-specific dataclass fields)
        field_names = set(getattr(param_cls, "__dataclass_fields__", {}).keys())
        filtered = {k: v for k, v in params.items() if k in field_names}

        # Most parameter classes inherit StrategyParameters and implement from_dict.
        if hasattr(param_cls, "from_dict"):
            self.parameters = param_cls.from_dict(filtered)  # type: ignore[attr-defined]
        else:
            # Fallback: set attributes on the existing object
            for k, v in filtered.items():
                if hasattr(self.parameters, k):
                    setattr(self.parameters, k, v)
        
        # Update strategy-specific parameters
        self.set_strategy_specific_params(params)
    
    def get_parameter_bounds(self) -> Dict[str, Tuple[float, float]]:
        """Get bounds for all parameters."""
        bounds = self.parameters.get_bounds()
        # Subclasses should override to add strategy-specific bounds
        return bounds
    
    def get_performance_summary(self) -> Dict[str, Any]:
        """Get summary of trading performance."""
        if not self.trades:
            return {
                'total_trades': 0,
                'total_return_pct': 0,
                'win_rate': 0,
                'avg_pnl_pct': 0,
                'max_drawdown_pct': 0
            }
        
        pnls = [t.pnl_pct for t in self.trades]
        wins = [p for p in pnls if p > 0]
        losses = [p for p in pnls if p < 0]
        
        # Calculate drawdown
        cumulative = np.cumsum(pnls)
        peak = np.maximum.accumulate(cumulative)
        drawdown = peak - cumulative
        max_drawdown = np.max(drawdown) if len(drawdown) > 0 else 0
        
        return {
            'total_trades': len(self.trades),
            'winning_trades': len(wins),
            'losing_trades': len(losses),
            'total_return_pct': sum(pnls),
            'win_rate': len(wins) / len(self.trades) if self.trades else 0,
            'avg_pnl_pct': np.mean(pnls),
            'avg_win_pct': np.mean(wins) if wins else 0,
            'avg_loss_pct': np.mean(losses) if losses else 0,
            'max_drawdown_pct': max_drawdown,
            'profit_factor': abs(sum(wins) / sum(losses)) if losses and sum(losses) != 0 else float('inf'),
            'avg_holding_period': np.mean([t.holding_period for t in self.trades]),
            'final_capital': self.current_capital
        }
    
    def to_json(self) -> str:
        """Serialize strategy state to JSON."""
        return json.dumps({
            'name': self.name,
            'parameters': self.get_all_parameters(),
            'initial_capital': self.initial_capital,
            'current_capital': self.current_capital,
            'trades': [t.to_dict() for t in self.trades],
            'performance': self.get_performance_summary()
        }, indent=2, default=str)
